package dev.razafindratelo.tapakilaBackend.entity.enums;

public enum TimeZone {
    //  UTC -12 to UTC -1
    UTC_MINUS_12_BAKER_ISLAND,
    UTC_MINUS_11_SAMOA_TIME,
    UTC_MINUS_10_HAWAII_ALEUTIAN_STANDARD_TIME,
    UTC_MINUS_9_ALASKA_STANDARD_TIME,
    UTC_MINUS_8_PACIFIC_STANDARD_TIME,
    UTC_MINUS_7_MOUNTAIN_STANDARD_TIME,
    UTC_MINUS_6_CENTRAL_STANDARD_TIME,
    UTC_MINUS_5_EASTERN_STANDARD_TIME,
    UTC_MINUS_4_ATLANTIC_STANDARD_TIME,
    UTC_MINUS_3_ARGENTINA_TIME,
    UTC_MINUS_2_SOUTH_GEORGIA_TIME,
    UTC_MINUS_1_AZORES_TIME,

    //  UTC +0
    UTC_0_GREENWICH_MEAN_TIME,
    UTC_0_WESTERN_EUROPEAN_TIME,

    //  UTC +1 to UTC +5
    UTC_1_CENTRAL_EUROPEAN_TIME,
    UTC_1_WEST_AFRICA_TIME,
    UTC_2_EASTERN_EUROPEAN_TIME,
    UTC_2_CENTRAL_AFRICA_TIME,
    UTC_3_MOSCOW_STANDARD_TIME,
    UTC_3_EAST_AFRICA_TIME,
    UTC_3_30_IRAN_STANDARD_TIME,
    UTC_4_UNITED_ARAB_EMIRATES_TIME,
    UTC_4_30_AFGHANISTAN_TIME,
    UTC_5_PAKISTAN_STANDARD_TIME,
    UTC_5_30_INDIA_STANDARD_TIME,
    UTC_5_45_NEPAL_TIME,

    //  UTC +6 to UTC +10
    UTC_6_BANGLADESH_STANDARD_TIME,
    UTC_6_30_MYANMAR_TIME,
    UTC_7_INDOCHINA_TIME,
    UTC_8_CHINA_STANDARD_TIME,
    UTC_8_30_NORTH_KOREA_TIME,
    UTC_9_JAPAN_STANDARD_TIME,
    UTC_9_30_AUSTRALIA_CENTRAL_STANDARD_TIME,
    UTC_10_EASTERN_AUSTRALIA_STANDARD_TIME,

    //  UTC +11 to UTC +14
    UTC_11_SOLOMON_ISLANDS_TIME,
    UTC_12_NEW_ZEALAND_STANDARD_TIME,
    UTC_12_FIJI_TIME,
    UTC_13_TONGA_TIME,
    UTC_14_KIRIBATI_TIME;
}
